name: Check Daily Tomato

on:
  schedule:
    - cron: '0 17 * * *' # 5PM GMT daily
  workflow_dispatch:      # allows manual runs too

jobs:
  check_daily_tomato:
    runs-on: ubuntu-latest

    steps:
      - name: Check redirect
        id: check
        run: |
          final_url=$(curl -Ls -o /dev/null -w %{url_effective} https://www.rottentomatoes.com/daily/)
          echo "Final URL after redirects: $final_url"

          if [[ "$final_url" == "https://editorial.rottentomatoes.com/otg-article/daily-tomato-will-return/" ]]; then
            echo "ALERT=false" >> $GITHUB_OUTPUT
          else
            echo "ALERT=true" >> $GITHUB_OUTPUT
            echo "Redirected to unexpected URL: $final_url" > message.txt
          fi


      - name: Send Email if Alert Needed
        if: steps.check.outputs.ALERT == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🧃 Daily Tomato is BACK!"
          to: ${{ secrets.REPO_OWNER_EMAIL }}
          from: "GitHub Action <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            The Daily Tomato page has changed. 
            Check it here: https://www.rottentomatoes.com/daily/
